FROM python:3.9-slim

WORKDIR /darknet

COPY requirements.txt /darknet/requirements.txt

RUN pip install -r requirements.txt

COPY . /darknet/app/client/

EXPOSE 8000

CMD ["fastapi", "run", "app/client/app.py"]
